using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Lime.Protocol.Network
{
    public class AsyncQueue<T> : IAsyncQueue<T>
    {
        #region Private fields

        private ConcurrentQueue<T> _bufferQueue;
        private ConcurrentQueue<TaskCompletionSource<T>> _promisesQueue;
        private object _syncRoot = new object();
        private int _promisesLimit;
        private int _bufferLimit;

        #endregion

        #region Constructor

        public AsyncQueue()
            : this(0, 0)
        {

        }

        public AsyncQueue(int promisesLimit, int bufferLimit)
        {
            _promisesLimit = promisesLimit;
            _bufferLimit = bufferLimit;

            _bufferQueue = new ConcurrentQueue<T>();
            _promisesQueue = new ConcurrentQueue<TaskCompletionSource<T>>();
        }

        #endregion

        #region IAsyncQueue<T> Members

        /// <summary>
        /// Enqueues the specified item.
        /// </summary>
        /// <param name="item">The item.</param>
        public void Enqueue(T item)
        {
            TaskCompletionSource<T> promise;
            do
            {
                if (_promisesQueue.TryDequeue(out promise) &&
                    !promise.Task.IsCanceled &&
                    promise.TrySetResult(item))
                {
                    return;                                       
                }
            }
            while (promise != null);

            lock (_syncRoot)
            {
                if (_promisesQueue.TryDequeue(out promise) &&
                    !promise.Task.IsCanceled &&
                    promise.TrySetResult(item))
                {
                    return;
                }

                if (_bufferLimit != 0 &&
                    _bufferQueue.Count >= _bufferLimit)
                {
                    throw new InvalidOperationException("Queue buffer limit reached");
                }

                _bufferQueue.Enqueue(item);
            }            
        }

        /// <summary>
        /// Dequeues the asynchronous.
        /// </summary>
        /// <param name="cancellationToken">The cancellation token.</param>
        /// <returns></returns>
        public Task<T> DequeueAsync(CancellationToken cancellationToken)
        {
            T item;

            if (!_bufferQueue.TryDequeue(out item))
            {
                lock (_syncRoot)
                {
                    if (!_bufferQueue.TryDequeue(out item))
                    {
                        if (_promisesLimit != 0 &&
                            _promisesQueue.Where(p => !p.Task.IsCanceled).Count() >= _promisesLimit)
                        {
                            throw new InvalidOperationException("Queue promises limit reached");
                        }

                        var promise = new TaskCompletionSource<T>();
                        cancellationToken.Register(() => promise.TrySetCanceled());

                        _promisesQueue.Enqueue(promise);
                        this.PromiseAdded.RaiseEvent(this, EventArgs.Empty);

                        return promise.Task;
                    }
                }
            }

            return Task.FromResult(item);
        }

        /// <summary>
        /// Gets a value indicating whether this instance has promises.
        /// </summary>
        /// <value>
        /// <c>true</c> if this instance has promises; otherwise, <c>false</c>.
        /// </value>
        public bool HasPromises
        {
            get { return _promisesQueue.Where(p => !p.Task.IsCanceled).Count() > 0; }
        }

        /// <summary>
        /// Occurs when a new promise
        /// is generated by the queue
        /// </summary>
        public event EventHandler PromiseAdded;

        #endregion
    }

    public interface IAsyncQueue<T>
    {
        /// <summary>
        /// Enqueue a new item 
        /// in the queue
        /// </summary>
        /// <param name="item"></param>
        void Enqueue(T item);

        /// <summary>
        /// Takes an Task which can be a promise
        /// to a instance of T or an available instance of
        /// T, if buffered.
        /// </summary>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        Task<T> DequeueAsync(CancellationToken cancellationToken);

        /// <summary>
        /// Informs if 
        /// </summary>
        bool HasPromises { get; }

        /// <summary>
        /// Occurs when a new promise
        /// is generated by the queue
        /// </summary>
        event EventHandler PromiseAdded;
    }
}
